# Generated by Django 5.1.1 on 2024-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('BE', 'Salao Beleza'), ('CR', 'Curiosidade'), ('GR', 'Geral')], default='GR', max_length=2),
        ),
    ]
